# Generated by Django 5.0.2 on 2024-02-07 11:48
# Modified by Nacer-eddine 5.0.2 on 2024-02-07 14:05

from django.db import migrations
from django.contrib.auth import get_user_model

def create_admin_user(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser('admin@admin.com', 'admin', first_name='Admin', last_name='User', role='admin')

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
