# Generated by Django 5.0.2 on 2024-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
